### ISSUE TITLE
Create gh-pages branch

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/venice-editioncrafter-data#5]
@NickLaiacona, you should now have the right permissions to create a branch to start deploying a site (ie, like this one https://github.com/cu-mkp/editioncrafter/tree/gh-pages)

**Comment by NickLaiacona** [comment]
thanks, this is done, I ended up deploying the main branch to github pages and added the necessary data for EditionCrafter there. Also updated README with instructions on how to update the EditionCrafter data.
